In [1]:
import numpy as np

In [2]:
day02_inputs = "inputs/day02.txt"
with open(day02_inputs, 'r') as file:
    day02_data = file.readlines()
day02_data = [line.strip() for line in day02_data]

In [3]:
movement = {
    "U": [-1,0],
    "D": [1,0],
    "L": [0,-1],
    "R": [0, 1]
}

# part1

In [4]:
starting_button = 5
keypad = np.arange(1, 9+1)
keypad = np.reshape(keypad, (3, 3))
print(keypad)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
curr_button = starting_button
button_index = [int(val[0]) for val in np.where(keypad == curr_button)]
pressed_button = []
for row in day02_data:
    for instruct in row:
        move_amount = movement[instruct]
        intermediate_move = [sum(x) for x in zip(button_index, move_amount)]
        if 0 <= intermediate_move[0] < 3 and 0 <= intermediate_move[1] < 3:
            button_index = intermediate_move
    curr_row_final_button = str(keypad[button_index[0]][button_index[1]])
    pressed_button.append(curr_row_final_button)

bathroom_code = "".join(pressed_button)
print(f"bathroom code is {bathroom_code}")


bathroom code is 97289


# part2

In [6]:
starting_button = 5
keypad = np.array([0, 0, 1, 0, 0, 0, 2, 3, 4, 0, 5, 6, 7, 8, 9, 0, "A", "B", "C", 0, 0 , 0, "D", 0, 0])
keypad = np.reshape(keypad, (5, 5))
print(keypad)

[['0' '0' '1' '0' '0']
 ['0' '2' '3' '4' '0']
 ['5' '6' '7' '8' '9']
 ['0' 'A' 'B' 'C' '0']
 ['0' '0' 'D' '0' '0']]


In [7]:
curr_button = str(starting_button)
button_index = [int(val[0]) for val in np.where(keypad == curr_button)]
pressed_button = []
for row in day02_data:
    for instruct in row:
        move_amount = movement[instruct]
        intermediate_move = [sum(x) for x in zip(button_index, move_amount)]
        if 0 <= intermediate_move[0] < 5 and 0 <= intermediate_move[1] < 5:
            intermediate_val = (keypad[intermediate_move[0]][intermediate_move[1]])
            if intermediate_val != "0":
                button_index = intermediate_move
    curr_row_final_button = str(keypad[button_index[0]][button_index[1]])
    pressed_button.append(curr_row_final_button)

bathroom_code = "".join(pressed_button)
print(f"bathroom code is {bathroom_code}")

bathroom code is 9A7DC
